name: Basic Setup Go - Self hosted

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  basic-setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      # - uses: actions/setup-go@v6
      - uses: antontroshin/setup-go@windows-go-mod-cache
        with:
          go-version: '1.16.1'
      - run: go version
      - run: go run ./main.go
        continue-on-error: true