name: Self hosted - Checking with cache false for repeated invocations 

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - run: go mod download

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false