name: Check Latest Go Version

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v5
      # - uses: actions/setup-go@v6
      - uses: antontroshin/setup-go@windows-go-mod-cache
        with:
          go-version: '1.23'
          check-latest: true
      - run: go version
      - run: go run ./main.go
        continue-on-error: true