name: Reproduce error 722 - With alternative workaround

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Sync dependencies and download modules
        run: |
          go mod tidy
          go mod download

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod