name: Go toolchain version handling

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup-go:
    runs-on: ubuntu-latest
    # env:
    #   GOTOOLCHAIN: local  
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: matthewhughes934/setup-go@improve-toolchain-handling
        # uses: lmvysakh/setup-go@check_460pr_sol
        # uses: actions/setup-go@v5
        with:
          go-version: '1.21.8'
          # go-version-file: go.mod  
          # go-version-directive: go
           

      - name: go version
        run: go version

      - name: Run app
        run: go run ./main.go

      # - name: Clean Go module cache
      #   if: always()
      #   run: |
      #     go clean -modcache || true